import type { Metadata } from 'next'
import { DM_Mono } from 'next/font/google'
import './globals.css'
import Provider from '@/components/Provider'

const dmM = DM_Mono({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={dmM.className}>{children}</body>
      </Provider>
    </html>
  )
}
